### ISSUE TITLE
Size mismatch between rand_pmf and range(5) ?

### ISSUE THREAD

**Issue by Armandpl** [wandb/edu#51]
https://github.com/wandb/edu/blob/135f4f1033ba90abcef439f9654e199dfb5e470e/math-for-ml/03_probability/utils/tests/q03.py#L23

**Comment by charlesfrye** [comment]
thanks for flagging this! it turns out, some edits I made to `q03.py` didn't get committed, so there was actually an error in that test in addition to the mismatch you identified.
